### ISSUE TITLE
New to pac4j and Play Scala.

### ISSUE THREAD

**Issue by hiltonsungevity** [pac4j/play-pac4j-scala-demo#28]
Hi, I downloaded this repo today and am unable to get it to run.  Have not changed any code in the demo and am just trying "activator run" as directed in the README.  

Getting a typeError as follows: 
play.sbt.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : Option[org.pac4j.core.profile.CommonProfile]
 required: org.pac4j.core.profile.CommonProfile]

![screen shot 2016-01-25 at 3 28 51 pm](https://cloud.githubusercontent.com/assets/15201280/12568122/5fdb36c0-c378-11e5-9adf-14cf68788ab4.png)

**Comment by leleuj** [comment]
You're right: we made a change and did not update the demo. @hugovalk : can you handle the fix? Thanks

**Comment by leleuj** [comment]
If you haven't fixed it by yourself, I just updated the demo: https://github.com/pac4j/play-pac4j-scala-demo/commit/aced22888e9f5cb62c683912855844aa1478eadd
