### ISSUE TITLE
Heroku demo: Google OIDC: Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by fleminra** [pac4j/play-pac4j-scala-demo#37]
In the Heroku demo deployment, when I click on "Protected url by Google OpenID Connect : oidc/index.html", Google says:

> 400 . That’s an error.
> 
> Error: redirect_uri_mismatch
> 
> The redirect URI in the request, http://play-pac4j-scala-demo.herokuapp.com/callback?client_name=OidcClient, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/343992089165-i1es0qvej18asl33mvlbeq750i3ko32k.apps.googleusercontent.com?project=343992089165 to update the authorized redirect URIs.

**Comment by leleuj** [comment]
So far, only Facebook has been configured to work online (vs locally on your development station): https://github.com/pac4j/play-pac4j-scala-demo/blob/master/conf/heroku.conf

Any contribution will be appreciated.
