### ISSUE TITLE
com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Illegal key size

### ISSUE THREAD

**Issue by rorocco** [pac4j/play-pac4j-scala-demo#40]
Hi, 

when trying the demo, I'm getting the same exception as described here:

https://www.bountysource.com/issues/39021905-jwt-authentication-error-generate-a-jwt-token-after-being-authenticated

I installed "Java Cryptography Extension (JCE) Unlimited Strength" and also tried the form authentication. 

Any help is much appreciated!

Thanks

**Comment by leleuj** [comment]
I think you have an issue with your key: what's its length? It should be 32 (or maybe 64).

**Comment by rorocco** [comment]
Hi Leleuj, 

Thanks for your answer. I actually didn't modify the code at all. The key is "12345678901234567890123456789012", length 32. I'll debug some more and let you know my findings.

**Comment by leleuj** [comment]
Indeed, it's very strange: if the key size is correct and the "unlimited strength" has been installed, it should work. Keep us posted.

**Comment by rorocco** [comment]
Hi Leleuj,

Thanks again for your advise. It works just *fine*. I just installed the "Java Cryptography Extension (JCE) Unlimited Strength" files in the wrong directory. Sorry to bother you!

-- markus.

**Comment by leleuj** [comment]
Good to know.
