### ISSUE TITLE
No implementation for org.pac4j.play.store.PlaySessionStore was bound

### ISSUE THREAD

**Issue by aleksandrmelnyk** [pac4j/play-pac4j-scala-demo#43]
Hi there,
am trying to use only FormClient, and getting following:

1) No implementation for org.pac4j.play.store.PlaySessionStore was bound.
  while locating org.pac4j.play.store.PlaySessionStore
    for the 3rd parameter of controllers.AuthController.<init>(AuthController.scala:13)
  while locating controllers.AuthController
    for the 9th parameter of router.Routes.<init>(Routes.scala:54)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:222)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:409)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:404)
	at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$2(Injector.scala:117)
	at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:126)
	at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:117)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)

here is my security module:
```
val formClient = new FormClient("/api/loginForm", new SimpleTestUsernamePasswordAuthenticator())

    val clients = new Clients(formClient, new AnonymousClient())
    val config = new Config(clients)
    config.addAuthorizer("user", new RequireAnyRoleAuthorizer[Nothing]("ROLE_USER"))
    config.setHttpActionAdapter(new DefaultHttpActionAdapter())
    bind(classOf[Config]).toInstance(config)

    bind(classOf[PlaySessionStore]).to(classOf[PlayCacheSessionStore])

    val callbackController = new CallbackController()
    callbackController.setDefaultUrl("/?defaulturlafterlogout")
    callbackController.setMultiProfile(true)
    bind(classOf[CallbackController]).toInstance(callbackController)

    val logoutController = new LogoutController()
    logoutController.setDefaultUrl("/")
    bind(classOf[LogoutController]).toInstance(logoutController)
```

Any ideas what could be wrong? Sorry am new to play/scala/pac4j.

thanks, in advance.

**Comment by aleksandrmelnyk** [comment]
Apart from that is there docs to tuts on how to implement authentication with sql db (say postgresql)?

**Comment by aleksandrmelnyk** [comment]
and am just trying to check if user authed, like this:
```
class AuthController @Inject()(cc: MessagesControllerComponents, config: Config, sessionStore: PlaySessionStore)
                              (implicit executionContext: ExecutionContext) extends AbstractController(cc) {


  def authed() = Action { request =>
    val webContext = new PlayWebContext(request, sessionStore)
    val profileManager = new ProfileManager[CommonProfile](webContext)
    Ok(profileManager.isAuthenticated+"")
  }
}
```

**Comment by aleksandrmelnyk** [comment]
Sorry, No implementation for org.pac4j.play.store.PlaySessionStore was bound was fixed when I added play.modules.enabled += "modules.SecurityModule"

**Comment by aleksandrmelnyk** [comment]
but the qeustion is:
should I have implement Authenticator<UsernamePasswordCredentials> for postgresql db based auth, or is there something implemented already?

**Comment by leleuj** [comment]
For SQL: http://www.pac4j.org/docs/authenticators/sql.html
